export const MESSAGE = {
  AUTH: {
    REGISTER_SUCCESS:
      'Register successfully. Please check your email to verify your account.',
    EMAIL_VERIFICATION_SUCCESS:
      'Email verification successful. You can now log in.',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'User has been logged out successfully!',
    TOKEN_REFRESH_SUCCESS: 'Token has been refreshed successfully!',
    PASSWORD_RESET_SUCCESS:
      'Password has been reset successfully. Please log in again.',
    GET_PROFILE_SUCCESS: 'User profile retrieved successfully.',
    FORGOT_PASSWORD_SUCCESS: 'Password reset link has been sent to your email.',
  },

  USER: {
    PROFILE_UPDATE: 'User profile updated successfully',
    AVATAR_UPDATE: 'User avatar updated successfully',
    STATUS_UPDATE: 'User status updated successfully',
    USER_NOT_FOUND: 'User not found',
    USER_ALREADY_EXISTS: 'User with this email already exists',
    USER_EMAIL_VERIFICATION_SENT: 'Email verification link sent successfully',
    FETCH_ALL: 'All users retrieved successfully',
  },

  STUDENT: {
    STUDENT_LIST: 'All students retrieved successfully',
    STUDENT_INFO: 'Student information retrieved successfully',
    STUDENT_UPDATE: 'Student information updated successfully',
    STUDENT_DASHBOARD: 'Student dashboard data retrieved successfully',
    STUDENT_COMBO_ENROLLMENTS:
      'Student combo enrollments retrieved successfully',
    STUDENT_COURSE_ENROLLMENTS:
      'Student course enrollments retrieved successfully',
  },

  TEACHER: {
    TEACHER_LIST: 'All teachers retrieved successfully',
    NEW_TEACHERS_LIST: 'New pending teachers retrieved successfully',
    TEACHER_INFO: 'Teacher information retrieved successfully',
    TEACHER_UPDATE: 'Teacher information updated successfully',
    TEACHER_STATUS_UPDATE: 'Teacher status updated successfully',
    TEACHER_CREATE: 'New teacher created successfully',
    TEACHER_AVAILABILITY_UPDATE: 'Teacher availability updated successfully',
    TEACHER_CERTIFICATION_UPDATE: 'Teacher certification updated successfully',
  },

  COUPON: {
    CREATE_SUCCESS: 'Coupon created successfully',
    UPDATE_SUCCESS: 'Coupon updated successfully',
    DELETE_SUCCESS: 'Coupon deleted successfully',
    APPLY_SUCCESS: 'Coupon applied successfully',
    VALIDATION_SUCCESS: 'Coupon validated successfully',
  },

  BLOG: {
    BLOG_CATEGORY_CREATED: 'Blog category created successfully',
    BLOG_CATEGORY_UPDATED: 'Blog category updated successfully',
    BLOG_CATEGORY_DELETED: 'Blog category deleted successfully',
    BLOG_CATEGORY_FETCHED: 'Blog category fetched successfully',
    BLOG_CATEGORY_NOT_FOUND: 'Blog category not found',
    BLOG_CATEGORIES_FETCHED: 'Blog categories fetched successfully',
    BLOGS_FETCHED: 'Blogs fetched successfully',
    BLOG_FETCHED: 'Blog fetched successfully',
    BLOG_NOT_FOUND: 'Blog not found',
    BLOG_CREATED: 'Blog created successfully',
    BLOG_UPDATED: 'Blog updated successfully',
    BLOG_DELETED: 'Blog deleted successfully',
    BLOG_PUBLISHED: 'Blog published successfully',
    BLOG_ARCHIVED: 'Blog archived successfully',
    BLOG_DRAFTED: 'Blog moved to draft successfully',
    BLOG_STATUS_UPDATED: 'Blog status updated successfully',
    BLOG_UNAUTHORIZED: 'Not authorized to access this blog',
    BLOG_CANNOT_EDIT_PUBLISHED: 'Cannot edit published blog',
    BLOG_COMMENT_LIKED: 'Blog comment liked successfully',
    BLOG_COMMENT_UNLIKED: 'Blog comment unliked successfully',
    TEACHER_NOT_FOUND: 'Teacher not found',
    INVALID_IMAGE_URL: 'Invalid image URL format',
    BLOG_FEATURED: 'Featured blogs retrieved successfully',
  },

  BLOG_COMMENT: {
    COMMENT_ADDED: 'Comment added successfully',
    COMMENT_DELETED: 'Comment deleted successfully',
    COMMENT_NOT_FOUND: 'Comment not found',
    COMMENT_UPDATED: 'Comment updated successfully',
    COMMENT_UNAUTHORIZED: 'Not authorized to modify this comment',
    COMMENT_LIST: 'Comments retrieved successfully',
    REPLY_LIST: 'Replies retrieved successfully',
    REPLY_ADDED: 'Reply added successfully',
    REPLY_DELETED: 'Reply deleted successfully',
    REPLY_NOT_FOUND: 'Reply not found',
    REPLY_UPDATED: 'Reply updated successfully',
    REPLY_LIKED: 'Reply liked successfully',
    REPLY_UNLIKED: 'Reply unliked successfully',
  },

  COURSE: {
    CATEGORY_LIST: 'Course categories retrieved successfully',
    CATEGORY_CREATED: 'Course category created successfully',
    CATEGORY_UPDATED: 'Course category updated successfully',
    CATEGORY_DELETED: 'Course category deleted successfully',
    CATEGORY_FETCHED: 'Course category fetched successfully',
    CATEGORY_COURSE_COUNT: 'Course count by category retrieved successfully',
    COURSE_CREATED: 'Course created successfully',
    COURSE_UPDATED: 'Course updated successfully',
    COURSE_DELETED: 'Course deleted successfully',
    COURSE_FETCHED: 'Course fetched successfully',
    COURSE_LIST: 'Courses retrieved successfully',
    COURSE_FEATURED: 'Featured courses retrieved successfully',
    COURSE_FEATURED_UPDATED: 'Course feature status updated successfully',
    COURES_POPULAR: 'Popular courses retrieved successfully',
    COURSE_NEWEST: 'Newest courses retrieved successfully',
    COURSE_PUBLISHED: 'Course publication status updated successfully',
    THUMBNAIL_UPLOAD_SUCCESS: 'Course thumbnail uploaded successfully',
    COMBO_COURSE_CREATED: 'Combo course created successfully',
    COMBO_COURSE_UPDATED: 'Combo course updated successfully',
    COMBO_COURSE_DELETED: 'Combo course deleted successfully',
    COMBO_COURSE_FETCHED: 'Combo course fetched successfully',
    COMBO_COURSE_LIST: 'Combo courses retrieved successfully',
  },

  WRITING: {
    CREATE_SUCCESS: 'Writing exercise created successfully',
    UPDATE_SUCCESS: 'Writing exercise updated successfully',
    DELETE_SUCCESS: 'Writing exercise deleted successfully',
    RETRIEVE_SUCCESS: 'Writing exercise retrieved successfully',
    RETRIEVE_ALL_SUCCESS: 'Writing exercises retrieved successfully',
    SUBMIT_SUCCESS: 'Writing exercise submitted successfully',
    GRADE_SUCCESS: 'Writing submission graded successfully',
    GRADE_AI_SUCCESS: 'Writing graded by AI successfully',
    SUBMISSIONS_RETRIEVE_SUCCESS: 'Writing submissions retrieved successfully',
    EXERCISE_SUBMISSIONS_RETRIEVE_SUCCESS:
      'Writing exercise submissions retrieved successfully',
    NOT_FOUND: 'Writing exercise not found',
    MAX_ATTEMPTS_EXCEEDED: 'Maximum attempts exceeded for this exercise',
  },

  SPEAKING: {
    CREATE_SUCCESS: 'Speaking exercise created successfully',
    UPDATE_SUCCESS: 'Speaking exercise updated successfully',
    DELETE_SUCCESS: 'Speaking exercise deleted successfully',
    RETRIEVE_SUCCESS: 'Speaking exercise retrieved successfully',
    RETRIEVE_ALL_SUCCESS: 'Speaking exercises retrieved successfully',
    SUBMIT_SUCCESS: 'Speaking exercise submitted successfully',
    GRADE_SUCCESS: 'Speaking submission graded successfully',
    GRADE_AI_SUCCESS: 'Speaking graded by AI successfully',
    SUBMISSIONS_RETRIEVE_SUCCESS: 'Speaking submissions retrieved successfully',
    EXERCISE_SUBMISSIONS_RETRIEVE_SUCCESS:
      'Speaking exercise submissions retrieved successfully',
    NOT_FOUND: 'Speaking exercise not found',
    MAX_ATTEMPTS_EXCEEDED: 'Maximum attempts exceeded for this exercise',
  },

  FILES: {
    FILE_USER_AVATAR_UPLOADED: 'User avatar uploaded successfully',
    FILE_CERTIFICATE_UPLOADED: 'Certificate uploaded successfully',
    FILE_BLOG_IMAGE_UPLOADED: 'Blog image uploaded successfully',
    FILE_EXERCISE_IMAGE_UPLOADED: 'Exercise image uploaded successfully',
    FILE_COURSE_THUMBNAIL_UPLOADED: 'Course thumbnail uploaded successfully',
    FILE_LESSON_MATERIAL_UPLOADED: 'Lesson material uploaded successfully',
    FILE_AUDIO_UPLOADED: 'Audio file uploaded successfully',
    FILE_NOT_FOUND: 'File not found',
  },

  CERTIFICATE: {
    CERTIFICATE_GENERATED: 'Certificate generated successfully',
    CERTIFICATE_RETRIEVED: 'Certificates retrieved successfully',
    CERTIFICATE_NOT_FOUND: 'Certificate not found',
    CERTIFICATE_NOT_COMPLETED:
      'Combo must be 100% completed to generate certificate',
  },

  GENERAL: {
    OPERATION_SUCCESS: 'Operation completed successfully',
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'Access forbidden',
    NOT_FOUND: 'Resource not found',
    INTERNAL_ERROR: 'Internal server error',
  },

  ERROR: {
    INVALID_TOKEN: 'Invalid or expired token',
    INVALID_CREDENTIALS: 'Invalid email or password',
    USER_ALREADY_EXISTS: 'User already exists',
    USER_NOT_FOUND: 'User not found',
    EMAIL_NOT_VERIFIED: 'Email not verified',
    INSUFFICIENT_PERMISSIONS: 'Insufficient permissions',
    VALIDATION_ERROR: 'Validation error',
    UNEXPECTED_ERROR: 'An unexpected error occurred',
    DATABASE_ERROR: 'Database operation failed',
    REDIS_ERROR: 'Redis operation failed',
    FILE_UPLOAD_ERROR: 'File upload failed',
    FILE_NOT_FOUND: 'File not found',
    FILE_DELETE_ERROR: 'File deletion failed',
  },
};
